apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spotter
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 1
  readiness:
    path: isready
    initialDelay: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  kafka:
    pool: {{kafkaPool}}